name: Rust Deployment Workflow

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     # Setup key
#     - run: set -eu
#     - run: mkdir "$HOME/.ssh"
#     - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
#     - run: chmod 600 "$HOME/.ssh/key"

#     # Build
#     - run: cargo build --verbose

#     # Tests
#     - run: cargo test --verbose

    # - name: Deploy
      
          
on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    name: actix-github-action
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./target/release/rust-actix
          remote_path: ${{ secrets.DEPLOYPATH }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key:  ${{ secrets.SSHPRIVATE }}
          # remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}

