name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Deploy to remote  
      uses: root-glukhov/rust-actix  
      with:  
        local: target/release/rust-actix@latest
        remote: /home/new/rust-actix
        host: $  
        username: $  
        password: $
