name: Rust Deployment Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 194.58.102.193
        username: root
        key: ${{ secrets.REGRU_SECRET }}
        port: 22
        script: |
          cd new
          git pull origin master
          git status
          

